import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>Lets build hulu-clone</h1> */}

      {/* Header */}
      <Header />

      {/* Navbar */}
      <Nav />

      {/* Results */}
      <Results />


    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
}
